package com.foodie.orderservice.mapper;

import com.foodie.common.pojo.Driverorder;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriverorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driverorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderid") Integer orderid, @Param("driverid") Integer driverid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driverorder
     *
     * @mbg.generated
     */
    int insert(Driverorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driverorder
     *
     * @mbg.generated
     */
    List<Driverorder> selectAll();

    int batchinsert(List<Driverorder> record);
}