package com.foodie.orderservice.mapper.test;

import com.foodie.common.pojo.Ordertime;

import java.util.List;

public interface OrdertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertime
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertime
     *
     * @mbg.generated
     */
    int insert(Ordertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertime
     *
     * @mbg.generated
     */
    Ordertime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertime
     *
     * @mbg.generated
     */
    List<Ordertime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertime
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ordertime record);
}