package com.foodie.orderservice.mapper.test;

import com.foodie.common.pojo.Ordercomment;

import java.util.List;

public interface OrdercommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercomment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercomment
     *
     * @mbg.generated
     */
    int insert(Ordercomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercomment
     *
     * @mbg.generated
     */
    Ordercomment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercomment
     *
     * @mbg.generated
     */
    List<Ordercomment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordercomment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ordercomment record);
}