package com.foodie.orderservice.mapper.test;


import com.foodie.common.pojo.Orderstate;

import java.util.List;

public interface OrderstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderstate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderstate
     *
     * @mbg.generated
     */
    int insert(Orderstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderstate
     *
     * @mbg.generated
     */
    Orderstate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderstate
     *
     * @mbg.generated
     */
    List<Orderstate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderstate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orderstate record);


}