package com.foodie.common.pojo;

public class Driverorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driverorder.orderid
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driverorder.driverid
     *
     * @mbg.generated
     */
    private Integer driverid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driverorder.orderid
     *
     * @return the value of driverorder.orderid
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driverorder.orderid
     *
     * @param orderid the value for driverorder.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driverorder.driverid
     *
     * @return the value of driverorder.driverid
     *
     * @mbg.generated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driverorder.driverid
     *
     * @param driverid the value for driverorder.driverid
     *
     * @mbg.generated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }
}