package com.foodie.common.pojo;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.prouteid
     *
     * @mbg.generated
     */
    private Integer prouteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.passengerid
     *
     * @mbg.generated
     */
    private Integer passengerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.driverid
     *
     * @mbg.generated
     */
    private Integer driverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.carid
     *
     * @mbg.generated
     */
    private Integer carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pdrouteid
     *
     * @mbg.generated
     */
    private Integer pdrouteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderpayid
     *
     * @mbg.generated
     */
    private Integer orderpayid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderstateid
     *
     * @mbg.generated
     */
    private Integer orderstateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordertimeid
     *
     * @mbg.generated
     */
    private Integer ordertimeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordercommentid
     *
     * @mbg.generated
     */
    private Integer ordercommentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.prouteid
     *
     * @return the value of order.prouteid
     *
     * @mbg.generated
     */
    public Integer getProuteid() {
        return prouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.prouteid
     *
     * @param prouteid the value for order.prouteid
     *
     * @mbg.generated
     */
    public void setProuteid(Integer prouteid) {
        this.prouteid = prouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.passengerid
     *
     * @return the value of order.passengerid
     *
     * @mbg.generated
     */
    public Integer getPassengerid() {
        return passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.passengerid
     *
     * @param passengerid the value for order.passengerid
     *
     * @mbg.generated
     */
    public void setPassengerid(Integer passengerid) {
        this.passengerid = passengerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.driverid
     *
     * @return the value of order.driverid
     *
     * @mbg.generated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.driverid
     *
     * @param driverid the value for order.driverid
     *
     * @mbg.generated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.carid
     *
     * @return the value of order.carid
     *
     * @mbg.generated
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.carid
     *
     * @param carid the value for order.carid
     *
     * @mbg.generated
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pdrouteid
     *
     * @return the value of order.pdrouteid
     *
     * @mbg.generated
     */
    public Integer getPdrouteid() {
        return pdrouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pdrouteid
     *
     * @param pdrouteid the value for order.pdrouteid
     *
     * @mbg.generated
     */
    public void setPdrouteid(Integer pdrouteid) {
        this.pdrouteid = pdrouteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderpayid
     *
     * @return the value of order.orderpayid
     *
     * @mbg.generated
     */
    public Integer getOrderpayid() {
        return orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderpayid
     *
     * @param orderpayid the value for order.orderpayid
     *
     * @mbg.generated
     */
    public void setOrderpayid(Integer orderpayid) {
        this.orderpayid = orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderstateid
     *
     * @return the value of order.orderstateid
     *
     * @mbg.generated
     */
    public Integer getOrderstateid() {
        return orderstateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderstateid
     *
     * @param orderstateid the value for order.orderstateid
     *
     * @mbg.generated
     */
    public void setOrderstateid(Integer orderstateid) {
        this.orderstateid = orderstateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertimeid
     *
     * @return the value of order.ordertimeid
     *
     * @mbg.generated
     */
    public Integer getOrdertimeid() {
        return ordertimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertimeid
     *
     * @param ordertimeid the value for order.ordertimeid
     *
     * @mbg.generated
     */
    public void setOrdertimeid(Integer ordertimeid) {
        this.ordertimeid = ordertimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordercommentid
     *
     * @return the value of order.ordercommentid
     *
     * @mbg.generated
     */
    public Integer getOrdercommentid() {
        return ordercommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordercommentid
     *
     * @param ordercommentid the value for order.ordercommentid
     *
     * @mbg.generated
     */
    public void setOrdercommentid(Integer ordercommentid) {
        this.ordercommentid = ordercommentid;
    }
}