package com.foodie.common.pojo;

import java.util.Date;

public class Ordertime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertime.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertime.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertime.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertime.departtime
     *
     * @mbg.generated
     */
    private Date departtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertime.arrivetime
     *
     * @mbg.generated
     */
    private Date arrivetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertime.id
     *
     * @return the value of ordertime.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertime.id
     *
     * @param id the value for ordertime.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertime.starttime
     *
     * @return the value of ordertime.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertime.starttime
     *
     * @param starttime the value for ordertime.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertime.endtime
     *
     * @return the value of ordertime.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertime.endtime
     *
     * @param endtime the value for ordertime.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertime.departtime
     *
     * @return the value of ordertime.departtime
     *
     * @mbg.generated
     */
    public Date getDeparttime() {
        return departtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertime.departtime
     *
     * @param departtime the value for ordertime.departtime
     *
     * @mbg.generated
     */
    public void setDeparttime(Date departtime) {
        this.departtime = departtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertime.arrivetime
     *
     * @return the value of ordertime.arrivetime
     *
     * @mbg.generated
     */
    public Date getArrivetime() {
        return arrivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertime.arrivetime
     *
     * @param arrivetime the value for ordertime.arrivetime
     *
     * @mbg.generated
     */
    public void setArrivetime(Date arrivetime) {
        this.arrivetime = arrivetime;
    }
}