package com.foodie.common.pojo;

public class Orderstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderstate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderstate.finishstate
     *
     * @mbg.generated
     */
    private Byte finishstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderstate.itinerarystate
     *
     * @mbg.generated
     */
    private Integer itinerarystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderstate.cancelstate
     *
     * @mbg.generated
     */
    private Byte cancelstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderstate.pickupstate
     *
     * @mbg.generated
     */
    private Byte pickupstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderstate.id
     *
     * @return the value of orderstate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderstate.id
     *
     * @param id the value for orderstate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderstate.finishstate
     *
     * @return the value of orderstate.finishstate
     *
     * @mbg.generated
     */
    public Byte getFinishstate() {
        return finishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderstate.finishstate
     *
     * @param finishstate the value for orderstate.finishstate
     *
     * @mbg.generated
     */
    public void setFinishstate(Byte finishstate) {
        this.finishstate = finishstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderstate.itinerarystate
     *
     * @return the value of orderstate.itinerarystate
     *
     * @mbg.generated
     */
    public Integer getItinerarystate() {
        return itinerarystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderstate.itinerarystate
     *
     * @param itinerarystate the value for orderstate.itinerarystate
     *
     * @mbg.generated
     */
    public void setItinerarystate(Integer itinerarystate) {
        this.itinerarystate = itinerarystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderstate.cancelstate
     *
     * @return the value of orderstate.cancelstate
     *
     * @mbg.generated
     */
    public Byte getCancelstate() {
        return cancelstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderstate.cancelstate
     *
     * @param cancelstate the value for orderstate.cancelstate
     *
     * @mbg.generated
     */
    public void setCancelstate(Byte cancelstate) {
        this.cancelstate = cancelstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderstate.pickupstate
     *
     * @return the value of orderstate.pickupstate
     *
     * @mbg.generated
     */
    public Byte getPickupstate() {
        return pickupstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderstate.pickupstate
     *
     * @param pickupstate the value for orderstate.pickupstate
     *
     * @mbg.generated
     */
    public void setPickupstate(Byte pickupstate) {
        this.pickupstate = pickupstate;
    }
}