package com.foodie.common.pojo;

import java.util.Date;

public class Ordercomment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercomment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercomment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercomment.rate
     *
     * @mbg.generated
     */
    private String rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordercomment.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercomment.id
     *
     * @return the value of ordercomment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercomment.id
     *
     * @param id the value for ordercomment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercomment.content
     *
     * @return the value of ordercomment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercomment.content
     *
     * @param content the value for ordercomment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercomment.rate
     *
     * @return the value of ordercomment.rate
     *
     * @mbg.generated
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercomment.rate
     *
     * @param rate the value for ordercomment.rate
     *
     * @mbg.generated
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordercomment.time
     *
     * @return the value of ordercomment.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordercomment.time
     *
     * @param time the value for ordercomment.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}