package com.foodie.common.pojo;

import java.util.Date;

public class Orderpay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.paytime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.fare
     *
     * @mbg.generated
     */
    private Long fare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderpay.paytype
     *
     * @mbg.generated
     */
    private String paytype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.id
     *
     * @return the value of orderpay.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.id
     *
     * @param id the value for orderpay.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.userid
     *
     * @return the value of orderpay.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.userid
     *
     * @param userid the value for orderpay.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.state
     *
     * @return the value of orderpay.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.state
     *
     * @param state the value for orderpay.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.paytime
     *
     * @return the value of orderpay.paytime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.paytime
     *
     * @param paytime the value for orderpay.paytime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.fare
     *
     * @return the value of orderpay.fare
     *
     * @mbg.generated
     */
    public Long getFare() {
        return fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.fare
     *
     * @param fare the value for orderpay.fare
     *
     * @mbg.generated
     */
    public void setFare(Long fare) {
        this.fare = fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderpay.paytype
     *
     * @return the value of orderpay.paytype
     *
     * @mbg.generated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderpay.paytype
     *
     * @param paytype the value for orderpay.paytype
     *
     * @mbg.generated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }
}