package com.foodie.common.pojo;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.departureid
     *
     * @mbg.generated
     */
    private Integer departureid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.destinationid
     *
     * @mbg.generated
     */
    private Integer destinationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.distance
     *
     * @mbg.generated
     */
    private Integer distance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.timecost
     *
     * @mbg.generated
     */
    private Integer timecost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.toll
     *
     * @mbg.generated
     */
    private Integer toll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.orderid
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.id
     *
     * @return the value of route.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.id
     *
     * @param id the value for route.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.departureid
     *
     * @return the value of route.departureid
     *
     * @mbg.generated
     */
    public Integer getDepartureid() {
        return departureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.departureid
     *
     * @param departureid the value for route.departureid
     *
     * @mbg.generated
     */
    public void setDepartureid(Integer departureid) {
        this.departureid = departureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.destinationid
     *
     * @return the value of route.destinationid
     *
     * @mbg.generated
     */
    public Integer getDestinationid() {
        return destinationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.destinationid
     *
     * @param destinationid the value for route.destinationid
     *
     * @mbg.generated
     */
    public void setDestinationid(Integer destinationid) {
        this.destinationid = destinationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.distance
     *
     * @return the value of route.distance
     *
     * @mbg.generated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.distance
     *
     * @param distance the value for route.distance
     *
     * @mbg.generated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.timecost
     *
     * @return the value of route.timecost
     *
     * @mbg.generated
     */
    public Integer getTimecost() {
        return timecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.timecost
     *
     * @param timecost the value for route.timecost
     *
     * @mbg.generated
     */
    public void setTimecost(Integer timecost) {
        this.timecost = timecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.toll
     *
     * @return the value of route.toll
     *
     * @mbg.generated
     */
    public Integer getToll() {
        return toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.toll
     *
     * @param toll the value for route.toll
     *
     * @mbg.generated
     */
    public void setToll(Integer toll) {
        this.toll = toll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.orderid
     *
     * @return the value of route.orderid
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.orderid
     *
     * @param orderid the value for route.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.type
     *
     * @return the value of route.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.type
     *
     * @param type the value for route.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }
}