package com.foodie.common.pojo;

public class Site {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.orderid
     *
     * @mbg.generated
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.routeid
     *
     * @mbg.generated
     */
    private Integer routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.id
     *
     * @return the value of site.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.id
     *
     * @param id the value for site.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.name
     *
     * @return the value of site.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.name
     *
     * @param name the value for site.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.longitude
     *
     * @return the value of site.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.longitude
     *
     * @param longitude the value for site.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.latitude
     *
     * @return the value of site.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.latitude
     *
     * @param latitude the value for site.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.orderid
     *
     * @return the value of site.orderid
     *
     * @mbg.generated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.orderid
     *
     * @param orderid the value for site.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.routeid
     *
     * @return the value of site.routeid
     *
     * @mbg.generated
     */
    public Integer getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.routeid
     *
     * @param routeid the value for site.routeid
     *
     * @mbg.generated
     */
    public void setRouteid(Integer routeid) {
        this.routeid = routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site.type
     *
     * @return the value of site.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site.type
     *
     * @param type the value for site.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }
}